### ISSUE TITLE
Containerized postgres

### ISSUE THREAD

**Issue by tcibinan** [nikita715/gitplag#2]
Currently, a local deployment of the gitplag application requires a postgres database to be available on the host machine. It makes a deployment of the application quite tedious.

To make things easier you can use [containerized postgres](https://hub.docker.com/_/postgres) database with a mounted directory to store the postgres data locally on host.

Moreover, while you have two containers in your application the use of of [docker-compose](https://docs.docker.com/compose/overview/) can be of help. An example of docker-compose file for a similar project can be found [here](https://github.com/tcibinan/flaxo/blob/dev/docker/compose/docker-compose.yml).

**Comment by nikita715** [comment]
Thanks for the issue! I've implemented a docker-compose with Postgres in a container, so these features will be available in the next release.

**Comment by tcibinan** [comment]
This is great, thank you!
